package ru.itis.androidplugin.view;

import com.intellij.ide.plugins.PluginManager;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ru.itis.androidplugin.elements.MaterialChildRecyclerView;
import ru.itis.androidplugin.elements.MaterialItem;
import ru.itis.androidplugin.elements.MaterialRecyclerView;
import ru.itis.androidplugin.generation.LayoutGenerator;
import ru.itis.androidplugin.settings.GenerateClass;
import ru.itis.androidplugin.settings.PluginProject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import com.intellij.openapi.diagnostic.Logger;

public class CreateAdapterDialog extends JDialog {
    private JPanel contentPane;
    private JTextField newItemJTextField;
    private JButton createLayoutButton;
    private JLabel itemTitleJLabel;
    private MainView mainView;
    private MaterialItem parentRecyclerView;
    private MaterialItem childRecyclerView;

    public CreateAdapterDialog(MainView mainView, MaterialItem parentRecyclerView) {
        this.mainView = mainView;
        this.parentRecyclerView = parentRecyclerView;
        init();
    }

    private void init() {
        setContentPane(contentPane);
        setModal(true);
        setLocationRelativeTo(null);

        childRecyclerView = new MaterialChildRecyclerView();
        childRecyclerView.mLayoutPath = PluginProject.mLayoutPath;
        // parent - child connection
        childRecyclerView.setParent(parentRecyclerView);
        parentRecyclerView.setСhild(childRecyclerView);


        //mainView.itemParentViewJLabel.setVisible(true);
        //mainView.itemParentViewJLabel.setText(parentRecyclerView.mId);
        newItemJTextField.setText("item_" + parentRecyclerView.mId.toLowerCase());

        createLayoutButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                LayoutGenerator layoutGenerator = new LayoutGenerator();
                layoutGenerator.insertNewLayout(newItemJTextField.getText());
                dispose();

                childRecyclerView.setView(mainView);
                childRecyclerView.addItemToHistoryList(mainView);
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        itemTitleJLabel = new JLabel();
        itemTitleJLabel.setText("Recycler View Item layout");
        contentPane.add(itemTitleJLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        newItemJTextField = new JTextField();
        contentPane.add(newItemJTextField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        createLayoutButton = new JButton();
        createLayoutButton.setText("Create layout");
        contentPane.add(createLayoutButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
